---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanad-api
  labels:
    app: kanad-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kanad-api
  template:
    metadata:
      labels:
        app: kanad-api
    spec:
      containers:
      - name: api
        image: kanad/api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: kanad-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: kanad-secrets
              key: redis-url
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: kanad-secrets
              key: anthropic-api-key
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: kanad-secrets
              key: encryption-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanad-worker
  labels:
    app: kanad-worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kanad-worker
  template:
    metadata:
      labels:
        app: kanad-worker
    spec:
      containers:
      - name: worker
        image: kanad/worker:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: kanad-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: kanad-secrets
              key: redis-url
        resources:
          requests:
            memory: "2Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        command: ["celery", "-A", "workers.celery_app", "worker", "--loglevel=info", "--concurrency=4"]

---
apiVersion: v1
kind: Service
metadata:
  name: kanad-api-service
spec:
  selector:
    app: kanad-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kanad-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kanad-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
